apiVersion: v1
kind: Service
metadata:
  name: {{ include "autokueng.fullname" . }}-api
  labels:
    {{- include "autokueng.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Chart.Name }}-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autokueng.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/deployment: {{ .Chart.Name }}-api