apiVersion: v1
kind: Service
metadata:
  name: {{ include "autokueng.fullname" . }}-data
  labels:
    {{- include "autokueng.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Chart.Name }}-data
spec:
  type: {{ .Values.data.service.type }}
  ports:
    - port: {{ .Values.data.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "autokueng.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/deployment: {{ .Chart.Name }}-data