apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autokueng.fullname" . }}-data
  labels:
    {{- include "autokueng.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Chart.Name }}-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.data.storage }}
